version: "3.9"
services:
  web:
    build: .
    restart: always
    environment:
      VIRTUAL_HOST: test-mix.layoric.org
      LETSENCRYPT_HOST: test-mix.layoric.org
      LETSENCRYPT_EMAIL: layoric@layoric.org
networks:
  shared:
    external:
      name: webproxy
