name: CI

on:
  pull_request: {}
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: setup .net core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100

      - name: build and test
        run: dotnet test
        working-directory: ./TestMix.Tests

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
            push: true
            tags: ${{env.GITHUB_REPOSITORY}}:latest
